# Generated by Django 4.1.2 on 2022-10-20 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("things", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thing",
            name="description",
            field=models.TextField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="thing",
            name="quantity",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Cannot be less than 0"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Cannot be more than 100"
                    ),
                ]
            ),
        ),
    ]
